### ISSUE TITLE
[Enhancement] Commande d'import/export

### ISSUE THREAD

**Issue by fredth** [SkyFred/GL02_Adomy#2]
## Objectif : permettre à l'utilisateur d'exécuter via Node JS et le fichier app.js une commande d'import/export simple.

Entrée : un fichier au format csv ou ical.
Sortie : un fichier au format csv ou ical.

Cette commande permettra simplement de convertir un fichier, et de tester les fonctions d'import et d'export en les isolant des autres opérations.

**Comment by loyk03** [comment]
Nous avons créé deux commandes : 
-  La 1e permet de convertir un fichier CSV en un fichier au format ICAL ("convertCsvToIcal")
- La 2e permet de convertir un fichier iCal en un fichier au format CSV ("convertIcalToCsv").

Ces 2 commandes convertissent d'abord dans le format pivot de la librairie avant d'exporter.
Cependant, elles ne fonctionnent que pour les fichiers tests fournis par l'équipe d'implémentation du code.
En effet leur parser est totalement spécifique à ces fichiers ( voir ticket #4 ).
