### ISSUE TITLE
[Enhancement] Commande d'intersection

### ISSUE THREAD

**Issue by fredth** [SkyFred/GL02_Adomy#3]
## Objectif : permettre à l'utilisateur d'obtenir par une ligne de commande l'intersection de deux emplois du temps

Entrée : import de deux emplois du temps
Sortie : export du nouvel emploi du temps (résultat de l'intersection) en fichier ical ou csv

L'export du fichier permet de vérifier le bon fonctionnement de l'opération d'intersection.

**Comment by thiba** [comment]
Commande développée, l'utilisateur peut appeler la fonction calculerIntersection() via la commande intersection "chemin absolu du fichier".
Cependant, une erreur a lieu à l'exécution de la fonction, signalée dans un autre ticket.
