### ISSUE TITLE
[Enhancement] Commande union

### ISSUE THREAD

**Issue by fredth** [SkyFred/GL02_Adomy#4]
Objectif : permettre à l'utilisateur d'obtenir par une ligne de commande l'union de deux emplois du temps

Entrée : import de deux emplois du temps
Sortie : export du nouvel emploi du temps (résultat de l'union) en fichier ical ou csv

L'export du fichier permet de vérifier le bon fonctionnement de l'opération d'union.

**Comment by alexandrabey** [comment]
La commande a été crée, mais ne marche que pour le type de documents tests fournis. 
Ps : voir le ticket correspondant qui a été crée par la suite.
