### ISSUE TITLE
[Enhancement] Commande volume horaire

### ISSUE THREAD

**Issue by fredth** [SkyFred/GL02_Adomy#6]
Objectif : permettre à l'utilisateur d'obtenir par une ligne de commande le volume horaire d'un emploi du temps
Entrée : import d'un emploi du temps
Sortie : affichage du volume horaire de l'emploi du temps

L'affichage du volume horaire permet de vérifier le bon fonctionnement du calcul.

**Comment by alexandrabey** [comment]
Commande crée, taper "calculVolumeHoraire", avec le chemin du fichier correspondant.
