### ISSUE TITLE
[Enhancement] Commande nombre d'interventions

### ISSUE THREAD

**Issue by fredth** [SkyFred/GL02_Adomy#7]
Objectif : permettre à l'utilisateur d'obtenir par une ligne de commande le nombre d'interventions dans un emploi du temps

Entrée : import d'un emploi du temps
Sortie : affichage du nombre d'interventions dans l'emploi du temps

L'affichage permet de vérifier le bon fonctionnement du calcul.

**Comment by alexandrabey** [comment]
Commande crée dans l'interprétateur, "nombreInterventions".
